### ISSUE TITLE
Registration_MS: Crashed bei Elastix

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/Slice2Volume#6]
![Error messages](https://user-images.githubusercontent.com/61883896/79196625-b3e6d180-7e30-11ea-916a-bb5a7e9afcaf.png)

**Comment by schneidorlein** [comment]
I fixed this issue (there should not appear an error anymore) and the reworked version can be found under the branch "issue6" and the code is named as before (registration.ijm). Maybe Theresa can test it and give an OK if it works for you.

 It is intentionally that there is no last image in the result table, so that is no mistake.

**Comment by Theresa-S** [comment]
Läuft :-)
